name: Build

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Sign and Build Release Bundle
      env:
        KEY_FILE_PASSWORD: ls-personal
        KEY_ALIAS: key0
        KEY_PASSWORD: ls-personal
      run:
        ./gradlew assembleRelease
    - name: Retrieve Version
      run: |
        echo "version_name=$(./gradlew -q appVersionName)" >> $GITHUB_ENV
      id: android_version

    - name: Create Release on Github
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{env.version_name}}
        name: Release - ${{env.version_name}}
        generate_release_notes: true
        prerelease: true
        files: app/build/outputs/apk/release/*.apk
