name: Build

on:
  release: 
    types: prereleased
  workflow_dispatch:
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Sign and Build Release Bundle
      env:
        KEY_FILE_PASSWORD: ls-personal
        KEY_ALIAS: key0
        KEY_PASSWORD: ls-personal
      run:
        ./gradlew assembleRelease

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        tag: ${{ github.ref }}
        overwrite: true
        release_name: Release ${{ github.ref }}
        promote: true
